### ISSUE TITLE
Add DNG output for ipynb and Colab

### ISSUE THREAD

**Issue by ghost** [martin-marek/hdr-plus-pytorch#4]
Hi, thanks for implementing it. Could you please also add (LinearRaw) DNG output to the ipynb and Colab demo which would also preserve the metadata, color profile and lens/GainMap corrections?

**Comment by martin-marek** [comment]
Hi, do you have a specific library in mind that would do this? Currently, I'm using rawpy, which is just a Python wrapper around LibRaw. Can you load a DNG image using the current setup?

**Comment by ghost** [comment]
I think you could stack the images to a 16 bit TIFF and then just use exiftool to convert that file to a DNG, see https://github.com/gluijk/dng-from-tiff/blob/main/dngmaker.bat and https://github.com/antonwolf/dng_stacker/blob/master/dng_stacker.bat

**Comment by martin-marek** [comment]
Since this is more of a research-oriented repository, I don't want to add too much complexity related to image formats. My other HDR+ repository [hdr-plus-swift](https://github.com/martin-marek/hdr-plus-swift) provides *much* better output quality but it also has thousands of lines of source code and is difficult to experiment with. It has really good DNG support but unfortunately it's Mac only.

If you really want good DNG support with this repository, I suggest you create your own fork.

**Comment by ghost** [comment]
Got it, thanks
